### ISSUE TITLE
D1 mini V4: wrong power label on I2C connector pinout

### ISSUE THREAD

**Issue by ZsZs73** [wemos/docs#30]
Hi, just noticed that the power pin of I2C connector is labelled as VBUS, however it is connected to +3.3V according to the schematics.
VBUS is supposed to be +5V fed from USB port.
![wemos_d1_mini_v4_pinout](https://user-images.githubusercontent.com/7700436/150086178-707eb5cd-1504-4a45-bfff-67bd0c3f5cca.png)
![wemos_d1_mini_v4_schematics](https://user-images.githubusercontent.com/7700436/150086189-9c3a416b-f508-4728-bf06-895cf428724d.png)
.

**Comment by wemos** [comment]
THX. We fixed it.
